---
title: "Tech Talks Meetup Group"
baseURL: "https://example.org/"
theme: "hugo-theme-zen"
languageCode: "en-US"
defaultContentLanguage: "en"
pluralizelisttitles: false
removePathAccents: true
paginate: 10
paginatePath: "page"
rssLimit: 20
author:
  name: "Tech Talks Admin"
  url: "https://tech-talks-sc.netlify.com"
  avatar: "path/to/some-image.jpg"

outputs:
  home: ["HTML","RSS", "JSON"]
  section: ["HTML","RSS", "JSON"]

params:
  contact: "info@example.org"
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  description: "The zen theme for Hugo example site."
  dateformat: "2 January, 2006"
  favicon: "icon-64.png"
  feedlinks: true
  footer: "Powered by [Hugo](https://gohugo.io/) and the [Zen theme](https://github.com/frjo/hugo-theme-zen). <a href=\"https://github.com/abhisek/tech-talks-web\" target=\"_blank\"><img width=\"149\" height=\"149\" src=\"https://github.blog/wp-content/uploads/2008/12/forkme_right_green_007200.png?resize=149%2C149\" style=\"position:absolute;top:0;right:0;\" alt=\"Fork me on GitHub\"></a>"
  icon: "apple-touch-icon-180.png"
  image: "apple-touch-icon-180.png"
  imageMaxWidth: 400
  jquery: true
  mobileMenu: true
  poweredby: false
  search: true
  searchSize: 20
  sidebar: true
  submitted: true
  logo: false
